baseURL = "https://arkencl.github.io/"
title = "arkencl"
publishDir = "docs"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Georg Göring"
    info = "Full Stack Developer"
    description = "Georg Göring's portfolio and blog site"
    keywords = "blog,developer,personal"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "One step from Eden"

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/arkencl"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/arkencl/"
[[params.social]]
    name = "Xing"
    icon = "fab fa-xing fa-2x"
    weight = 3
    url = "https://xing.com/profile/Georg_Goering2/cv"
[[params.social]]
    name = "Linkedin"
    icon = "fab fa-linkedin-in fa-2x"
    weight = 4
    url = "https://linkedin.com/in/georg-göring-173b681a8/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 2
    url  = "/posts/"
[[menu.main]]
    name = "Bucket"
    weight = 3
    url = "/bucket/"
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
